<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>android-arm64</RuntimeIdentifier>
    <UseInterpreter>true</UseInterpreter>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>link</TrimMode>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidKeyStore>false</AndroidKeyStore>
    <AndroidVersion>33</AndroidVersion>
    <TargetAndroidVersion>33</TargetAndroidVersion>
    <AssemblyName>ai-sandbox</AssemblyName>
    <RootNamespace>AISandbox</RootNamespace>
    <ApplicationTitle>AI Sandbox</ApplicationTitle>
    <ApplicationId>com.dlabca.aisandbox</ApplicationId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.Android" Version="3.8.1.263" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.1.263" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Content\" />
  </ItemGroup>
</Project>